apiVersion: apps/v1
kind: Deployment
metadata:
  name: clap-fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clap-fastapi
  template:
    metadata:
      labels:
        app: clap-fastapi
    spec:
      containers:
      - name: clap-fastapi
        image: clap-fastapi:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 200m
            memory: 128Mi
          limits:
            cpu: 2000m
            memory: 256Mi
